# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b33f398043bc83447d59e28b05ac7539f05618bd045b636d8f1f52da4065455ecf90b4698cbc264706d141bec68aedb76a572241a585af1babc3e6d7628f44e4

test:
  secret_key_base: b201801c8a6b4c713991543ce5cdc0ef921037de1b255ad82a9175a0afd4bd1cd6ad4ef3ba3b8ab1ad495b7af927d23c55beec3118a219075f8f9da4f3a4cf5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
